name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}} 
      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext zip unzip
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
          unzip Images.zip
          zip -r Flow.Launcher.Plugin.FancyEmoji.zip . -x '*.git*'
      - name: Publish
        if: success() && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: 'Flow.Launcher.Plugin.FancyEmoji.zip'
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}